### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by righthandedmouse** [Kenny2github/discord-ext-slash#7]
![image](https://user-images.githubusercontent.com/69902176/132501714-2050e254-9510-4078-bccd-8f43d19f9b5d.png)

**Comment by retronbv** [comment]
When you add your bot to your server make sure you select application.commands **AND** bot
![C8FE22A4-AB5E-4A8F-8ACC-7D991ECEA58F](https://user-images.githubusercontent.com/49005044/132525366-e84f868e-6abf-482b-bc09-36eb7f5f46d2.jpeg)
